---
title: "delineateWatershed_all_points"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(progressr)
library(terrainr)
library(readr)
library(devtools)
devtools::install_github("markwh/streamstats")
library(streamstats)


```

Import Data

```{r}

AllWatersheds_LatLong <- read_csv("AllWatersheds_LatLong.csv")

AllWatersheds_LatLong <- AllWatersheds_LatLong %>%
  mutate(Unique_Site_ID = paste0(LTER, "_", Stream.Site)) 

AllWatersheds_LatLong$Unique_Site_ID <- as.factor(AllWatersheds_LatLong$Unique_Site_ID)

AllWatersheds_LatLong %>% group_by(Unique_Site_ID)


```

## Sucessful points

```{r}


AND_GSMACK <- delineateWatershed(xlocation = -122.17282, ylocation = 44.22054, crs = 4326,
includeparameters = "true")

AND_GSMACK_params <- AND_GSMACK$parameters

AND_GSMACK_params <- AND_GSMACK_params %>% mutate(Unique_site_id = "AND_GSMACK")
#Cool map!
map_AND_GSMACK <- leafletWatershed(AND_GSMACK)

#Looking at all the available features
features_AND_GSMACK <- pullFeatureCollection(AND_GSMACK)

#Convert watershed to sp
# Returns either SpatialPointsDataFrame or SpatialPolygonsDataFrame

sp_AND_GSMACK <- toSp(AND_GSMACK)

shp_AND_GSMACK <- writeShapefile(AND_GSMACK, layer = "AND_GSMACK")



```

```{r}


AND_GSWS06 <- delineateWatershed(xlocation = -122.18071, ylocation = 44.26151, crs = 4326,
includeparameters = "true")

AND_GSWS06_params <- AND_GSWS06$parameters

AND_GSWS06_params <- AND_GSWS06_params %>% mutate(Unique_site_id = "AND_GSWS06")
#Cool map!
map_AND_GSWS06 <- leafletWatershed(AND_GSWS06)

#Looking at all the available features
features_AND_GSWS06 <- pullFeatureCollection(AND_GSWS06)

#Convert watershed to sp
# Returns either SpatialPointsDataFrame or SpatialPolygonsDataFrame

sp_AND_GSWS06 <- toSp(AND_GSWS06)

shp_AND_GSWS06 <- writeShapefile(AND_GSWS06, layer = "AND_GSWS06")



```



```{r}

AND_GSWS02 <- delineateWatershed(xlocation = -122.17282, ylocation = 44.22054, crs = 4326,
includeparameters = "true")

AND_GSWS02_params <- AND_GSWS02$parameters

AND_GSWS02_params <- AND_GSWS02_params %>% mutate(Unique_site_id = "AND_GSWS02")


```



```{r}


AND_GSWS07 <- delineateWatershed(xlocation = -122.17526, ylocation = 44.26464, crs = 4326,
includeparameters = "true")

AND_GSWS07_params <- AND_GSWS07$parameters

AND_GSWS07_params <- AND_GSWS07_params %>% mutate(Unique_site_id = "AND_GSWS07")


```

```{r}


AND_GSWS08 <- delineateWatershed(xlocation = -122.17079, ylocation = 44.26629, crs = 4326,
includeparameters = "true")

AND_GSWS08_params <- AND_GSWS08$parameters

AND_GSWS08_params <- AND_GSWS08_params %>% mutate(Unique_site_id = "AND_GSWS08")


```

```{r}


AND_GSWS09 <- delineateWatershed(xlocation = -122.25880, ylocation = 44.20119, crs = 4326,
includeparameters = "true")

AND_GSWS09_params <- AND_GSWS09$parameters

AND_GSWS09_params <- AND_GSWS09_params %>% mutate(Unique_site_id = "AND_GSWS09")


```


## UMR

```{r}

#UMR_BK01.0M is the real unique id but I replaced the "." with a "_"

UMR_BK01_0M <- delineateWatershed(xlocation = -91.25103, ylocation = 43.84128, crs = 4326,
includeparameters = "true", rcode = "WI")

UMR_BK01_0M_params <- UMR_BK01_0M$parameters

UMR_BK01_0M_params <- UMR_BK01_0M_params %>% mutate(Unique_site_id = "UMR_BK01.0M")


```


```{r}


UMR_CH00.1M <- delineateWatershed(xlocation = -92.08417, ylocation = 44.4102, crs = 4326,
includeparameters = "true", rcode = "WI")

UMR_CH00.1M_params <- UMR_CH00.1M$parameters

UMR_CH00.1M_params <- UMR_CH00.1M_params %>% mutate(Unique_site_id = "UMR_CH00.1M")


```

## Trying Luquillo just to confirm it won't work outside US

```{r}


LUQ_QS <- delineateWatershed(xlocation = 	18.32000, ylocation = -65.82000, crs = 4326,
includeparameters = "true")




```